name: Branch Name Validation

on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Name
        run: |
          branch_name="${{ github.head_ref }}"
          
          # Valid patterns
          if [[ $branch_name =~ ^(feature|bugfix|hotfix|release)/[A-Za-z0-9._-]+$ ]]; then
            echo "✅ Valid branch name: $branch_name"
            exit 0
          else
            echo "❌ Invalid branch name: $branch_name"
            echo "Expected format: (feature|bugfix|hotfix|release)/[A-Za-z0-9._-]+"
            exit 1
          fi