name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - future
          - active

jobs:
  deployment-lifecycle-validation:
    name: Deployment Lifecycle Validation
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.validate.outputs.is_valid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Deployment Lifecycle Validation
        id: validate
        uses: ./.github/actions/deployment-lifecycle-validation
        with:
          environment: ${{ inputs.environment }}
          branch: ${{ github.ref_name }}

      - name: Check Validation Result
        if: steps.validate.outputs.is_valid != 'true'
        run: |
          echo "::error::Deployment lifecycle validation failed"
          exit 1

  branch-validation:
    name: Branch Validation
    runs-on: ubuntu-latest
    needs: deployment-lifecycle-validation
    outputs:
      is_valid: ${{ steps.validate-branch.outputs.is_valid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Branch Validation
        id: validate-branch
        uses: ./.github/actions/branch-validation
        with:
          branch: ${{ github.ref_name }}
          environment: ${{ inputs.environment }}

      - name: Check Branch Validation Result
        if: steps.validate-branch.outputs.is_valid != 'true'
        run: |
          echo "::error::Branch validation failed"
          exit 1

  release-check:
    name: Future or Active Release Check
    runs-on: ubuntu-latest
    needs: branch-validation
    outputs:
      is_valid: ${{ steps.check-release.outputs.is_valid }}
      release_id: ${{ steps.check-release.outputs.release_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Release Status
        id: check-release
        uses: ./.github/actions/release-check
        with:
          release_type: ${{ inputs.release_type }}
          environment: ${{ inputs.environment }}

      - name: Check Release Validation Result
        if: steps.check-release.outputs.is_valid != 'true'
        run: |
          echo "::error::Release check failed - no valid future or active release found"
          exit 1

  deploy-to-future-release:
    name: Deploy to Future Release
    runs-on: ubuntu-latest
    needs: release-check
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Release
        uses: ./.github/actions/deploy-to-release
        with:
          release_id: ${{ needs.release-check.outputs.release_id }}
          environment: ${{ inputs.environment }}
          duration: 'unlimited'

      - name: Deployment Summary
        run: |
          echo "## Deployment Successful! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release ID**: ${{ needs.release-check.outputs.release_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Duration**: Unlimited" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

